activities/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from views import Act_List, Act_Create, Act_Detail, Act_Update, Act_Delete, ajax_load_groups

urlpatterns = [
    url(r'^$', Act_List.as_view(), name='list'),
    url(r'^create/$', Act_Create.as_view(), name='create'),
    url(r'^detail/(?P<pk>[0-9]+)$', Act_Detail.as_view(), name='detail'),
    url(r'^edit/(?P<pk>[0-9]+)$', Act_Update.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)$', Act_Delete.as_view(), name='delete'),
    url(r'^ajax/load-groups/$', ajax_load_groups, name='ajax_load_groups'),
]

groups/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from views import Group_List, Group_Create, Group_Detail, Group_Update, Group_Delete

urlpatterns = [
    url(r'^$', Group_List.as_view(), name='list'),
    url(r'^create/$', Group_Create.as_view(), name='create'),
    url(r'^detail/(?P<pk>[0-9]+)$', Group_Detail.as_view(), name='detail'),
    url(r'^edit/(?P<pk>[0-9]+)$', Group_Update.as_view(), name='update'),
    url(r'^delete/(?P<pk>[0-9]+)$', Group_Delete.as_view(), name='delete'),
]

sugipms/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from accounts.views import login_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^acts/', include('activities.urls', namespace='activities')),
    url(r'^login', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

groups/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from projects.models import Project

User = get_user_model()

# Create your models here.
class Group(models.Model):

   NAME_C = (
         ('CH', 'CABLING HORIZONTAL'),
         ('CV', 'CABLING VERTICAL'),
         ('HW', 'INSTALAÇÃO E CONFIGURAÇÃO DE HW'),
         ('INFRA', 'INFRA BÁSICA'),
         ('PLAN', 'PLANEJAMENTO'),
         ('SUGI', 'SUGI+ SERVIDORES'),
      )
   
   project = models.ForeignKey(Project, on_delete=models.CASCADE)
   name = models.CharField(max_length=8, choices=NAME_C, default='CH')
   description = models.TextField(max_length=60, null=True, blank=True)
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)
   
   def __unicode__(self):
      return self.get_group()

   def __str__(self):
      return self.get_group()

   def get_absolute_url(self):
      return reverse('groups:list')

   def get_group(self):
      for group in self.NAME_C:
         if group[0] == self.name:
            return group[1]

class GroupStatus(models.Model):

   group = models.ForeignKey(Group)
   start = models.DateField(default=timezone.now())
   end = models.DateField(default=timezone.now())
   duration = models.IntegerField(default=0)
   act_ended = models.IntegerField(default=0)
   act_program = models.IntegerField(default=0)
   act_late = models.IntegerField(default=0)
   act_total = models.IntegerField(default=0)
   deliveried = models.DecimalField(default=0, max_digits=2, decimal_places=2)
   target = models.DecimalField(default=0, max_digits=2, decimal_places=2)
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)

   def __unicode__(self):
      return self.group.name

   def __str__(self):
      return self.group.name

   class Meta:
        verbose_name_plural = "GroupStatus"

   

accounts/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import authenticate, get_user_model, login, logout
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Div, Submit, ButtonHolder, Button, HTML
User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField(label="Usuário:")
    password = forms.CharField(label="Senha:", widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'user-login'
        self.helper.form_method = 'POST'
        self.helper.form_action = ''
        self.helper.layout = Layout(
            Div(Div('username', css_class="col-4"), css_class="row"),
            Div(Div('password', css_class="col-4"), css_class="row"),
            Div(HTML("<br>"), css_class="row"),
            ButtonHolder(Submit('submit', 'Salvar', css_class='button white'), css_class='col-6')
            )

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if username and password:
            if not user:
                raise forms.ValidationError('This user does not exist')
            if not user.check_password(password):
                raise forms.ValidationError('Password incorrect')
            if not user.is_active:
                raise forms.ValidationError('User disabled')

        return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email')
    email2 = forms.EmailField(label='Confirm email')
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'email2', 'password']

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError('Emails must match')
        emails_qs = User.objects.filter(email=email)
        if emails_qs.exists():
            raise forms.ValidationError('Email already exists, please use other')
        return super(UserRegisterForm, self).clean(*args, **kwargs)

    # def clean_email2(self):
    #     email = self.cleaned_data.get('email')
    #     email2 = self.cleaned_data.get('email2')
    #     if email != email2:
    #         raise forms.ValidationError('Emails must match')
    #     emails_qs = User.objects.filter(email=email)
    #     if emails_qs.exists():
    #         raise forms.ValidationError('Email already exists, please use other')
    #     return email

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, get_user_model, login, logout
from .forms import UserLoginForm, UserRegisterForm

# Create your views here.
def login_view(request):
    title = 'Login'
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('rat:list')
    context_data = {
        'form': form,
        'title': title
    }
    return render(request, 'account_form.html', context_data)

def register_view(request):
    title = 'Register'
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password')
        user.set_password(password=password)
        user.save()
        new_user = authenticate(username=user.username, password=user.password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect('/')
    context_data = {
        'form': form,
        'title': title
    }
    return render(request, 'account_form.html', context_data)

def logout_view(request):
    logout(request)
    return redirect('/login')

templates/account_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block head_title %}
    {{block.super}}
{% endblock head_title %}


{% block javascript %}

{% endblock javascript %}



{% block content %}
<h1>RAT NET</h1>
<div class="row">
    <div class="col-12">
			{% crispy form %}
    </div>
</div>
{% endblock content %}

templates/activ_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{block.super}} | Atividades
{% endblock head_title %}


{% block javascript %}

 <script type="text/javascript">


  $( function() {
    $( ".dateinput" ).datepicker({
		monthNames: [ "Janeiro", "Fevereiro", "Março", "Abril", "Março", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" ]})
  } );
  
  </script>
  

  
{% endblock javascript %}


{% block content %}

<h1>Atividades</h1>
<div class="row">
    <div class="col-12">
		{% crispy form %}

		<input type="hidden" id="load_groups" value="{% url 'activities:ajax_load_groups' %}">
    </div>
</div>

  <script>
    $("#id_project").change(function () {
      var url = $("#load_groups").val();
      var projectId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'project': projectId
        },
        success: function (data) {
          $("#id_group").html(data);
        }
      });

    });
  </script>

{% endblock content %}

templates/activ_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{block.super}} | RAT
{% endblock head_title %}


{% block content %}
<h1>Detalhes da RAT</h1>
<div class="row">
    <div class="col-4">
        {{rat.chg}}
    </div>
</div>

{% endblock content %}

templates/activ_list.html
{% extends 'base.html' %}
{% block head_title %}
    {{block.super}} | Projects
{% endblock head_title %}

{% block javascript %} {% endblock javascript %}

{% block content %}

<h1>Lista de Atividades</h1>

<div class="row">
    <div class="col-12">
		<a class="btn btn-success btn-sm" href="{% url 'activities:create' %}" role="button">Nova Atividade</a>
        <br>
        <br>
        <table class="table table-sm table-hover table-bordered text-center">
          <thead>
            <tr class="table-success">
				<th scope="col">Projeto</th>
                <th scope="col">Grupo</th>
				<th scope="col">Ação</th>
				<th scope="col">Inicio Progamado</th>
				<th scope="col">Duração (dias)</th>
				<th scope="col">Término Progamado</th>
				<th scope="col">Status</th>
				<th scope="col">Ações</th>
            </tr>
          </thead>
            <tbody>
        {% for action in act_list %}
                <tr>
                    <th scope="row">{{action.group.project}}</th>
					<td>{{action.group.get_group}}</td>
					<td>{{action.action}}</td>
					<td>{{action.start_estimated | date:"d/M/y"}}</td>
					<td>{{action.duration_estimated}}</td>
					<td>{{action.end_estimated | date:"d/M/y"}}</td>
					<td>{{action.get_status}}</td>
                    <td>
						<a class="btn btn-primary btn-sm" href="{% url 'activities:update' pk=action.id %}" role="button"><i class="fa fa-edit"></i> Editar</a>
						<button type="button" onclick="deleteModal({{action.id}})" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remover</button>
						<input type="hidden" id="delete-{{action.id}}" value="{% url 'activities:delete' pk=action.id %}">
                    </td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<!-- Modal content-->
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Remover</h4>
                <button type="button" class="close" data-dismiss="modal"><span>×</span></button>

            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-danger" id="btn-confirm-delete" href="#" role="button">Sim, Remover</a>
                <button type="button"  class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

    <script type="text/javascript">
    function deleteModal(id){
		var deleteUrl = $("#delete-"+id)[0].baseURI + 'delete/' + id ;
        $("#btn-confirm-delete")[0].href = deleteUrl;
		console.log(deleteUrl)
        console.log($("#btn-confirm-delete"))
        $("#deleteModal").modal();
    };
    </script>


{% endblock content %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %} SUGI PMS {% endblock head_title %}</title>
    {% block extra_head %} {% endblock extra_head %}
</head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<style>
    {% block style %}
    {% endblock style %}
</style>

{% block javascript %}{% endblock javascript %}


<body>
<div class="container">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'projects:list' %}">Projetos</a></li>
		<li class="breadcrumb-item"><a href="{% url 'groups:list' %}">Grupos</a></li>
		<li class="breadcrumb-item"><a href="{% url 'activities:list' %}">Atividades</a></li>
        {% if not request.user.is_authenticated %}
            <li class="pull-right breadcrumb-item text-right"><a href="{% url 'login' %}">Login</a></li>
        {% else %}
            <li class="pull-right breadcrumb-item text-right"><a href="{% url 'logout' %}">Logout</a></li>
			<li class="pull-right breadcrumb-item text-left">{{request.user}} - {{request.user.first_name}} {{request.user.last_name}}</li>
        {% endif %}
    </ol>
</div>



{% include 'messages.html' %}


<div class="container">
    <div class="row">
        <div class="col-12">
            {% block content %}{% endblock content %}
        </div>
    </div>
</div>





</body>
</html>

templates/group_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{block.super}} | Projeto
{% endblock head_title %}


{% block javascript %}

 <script type="text/javascript">


  $( function() {
    $( ".dateinput" ).datepicker({
		monthNames: [ "Janeiro", "Fevereiro", "Março", "Abril", "Março", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" ]})
  } );
  
  </script>
  
{% endblock javascript %}


{% block content %}

<h1>Projeto</h1>
<div class="row">
    <div class="col-12">
		{% crispy form %}
    </div>
</div>

{% endblock content %}

templates/group_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{block.super}} | RAT
{% endblock head_title %}


{% block content %}
<h1>Detalhes da RAT</h1>
<div class="row">
    <div class="col-4">
        {{rat.chg}}
    </div>
</div>

{% endblock content %}

templates/group_dropdown_list_options.html
<option value="">---------</option>
{% for group in groups %}
<option value="{{ group.pk }}">{{ group.get_group }}</option>
{% endfor %}

templates/group_list.html
{% extends 'base.html' %}
{% block head_title %}
    {{block.super}} | Projects
{% endblock head_title %}

{% block javascript %} {% endblock javascript %}

{% block content %}

<h1>Lista de Grupos</h1>

<div class="row">
    <div class="col-12">
		<a class="btn btn-success btn-sm" href="{% url 'groups:create' %}" role="button">Novo Grupo</a>
        <br>
        <br>
        <table class="table table-sm table-hover table-bordered text-center">
          <thead>
            <tr class="table-success">
				<th scope="col">Projeto</th>
                <th scope="col">Nome</th>
				<th scope="col">Ações</th>
            </tr>
          </thead>
            <tbody>
        {% for group in group_list %}
                <tr>
                    <th scope="row">{{group.project}}</th>
					<td>{{group.get_group}}</td>
                    <td>
						<a class="btn btn-primary btn-sm" href="{% url 'groups:update' pk=group.id %}" role="button"><i class="fa fa-edit"></i> Editar</a>
						<button type="button" onclick="deleteModal({{group.id}})" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remover</button>
						<input type="hidden" id="delete-{{group.id}}" value="{% url 'groups:delete' pk=group.id %}">
                    </td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<!-- Modal content-->
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Remover</h4>
                <button type="button" class="close" data-dismiss="modal"><span>×</span></button>

            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-danger" id="btn-confirm-delete" href="#" role="button">Sim, Remover</a>
                <button type="button"  class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

    <script type="text/javascript">
    function deleteModal(id){
		var deleteUrl = $("#delete-"+id)[0].baseURI + 'delete/' + id ;
        $("#btn-confirm-delete")[0].href = deleteUrl;
		console.log(deleteUrl)
        console.log($("#btn-confirm-delete"))
        $("#deleteModal").modal();
    };
    </script>


{% endblock content %}

templates/messages.html
<div class="messages">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

templates/project_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{block.super}} | Projeto
{% endblock head_title %}


{% block javascript %}

 <script type="text/javascript">


  $( function() {
    $( ".dateinput" ).datepicker({
		monthNames: [ "Janeiro", "Fevereiro", "Março", "Abril", "Março", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" ]})
  } );
  
  </script>
  
{% endblock javascript %}


{% block content %}

<h1>Projeto</h1>
<div class="row">
    <div class="col-12">
		{% crispy form %}
    </div>
</div>

{% endblock content %}

templates/project_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
    {{block.super}} | RAT
{% endblock head_title %}


{% block content %}
<h1>Detalhes da RAT</h1>
<div class="row">
    <div class="col-4">
        {{rat.chg}}
    </div>
</div>

{% endblock content %}

templates/project_list.html
{% extends 'base.html' %}
{% block head_title %}
    {{block.super}} | Projects
{% endblock head_title %}

{% block javascript %} {% endblock javascript %}

{% block content %}

<h1>Lista de Projetos</h1>

<div class="row">
    <div class="col-12">
		<a class="btn btn-success btn-sm" href="{% url 'projects:create' %}" role="button">Novo Projeto</a>
        <br>
        <br>
        <table class="table table-sm table-hover table-bordered text-center">
          <thead>
            <tr class="table-success">
                <th scope="col">Nome</th>
                <th scope="col">Líder</th>
				<th scope="col">Início Estimado</th>
                <th scope="col">Conclusão Estimada</th>
                <th scope="col">Estado</th>
				<th scope="col">Ações</th>
            </tr>
          </thead>
            <tbody>
        {% for project in project_list %}
                <tr>
                    <th scope="row">{{project.name}}</th>
					<td>{{project.get_project_leader}}</td>
                    <td>{{project.start_estimated | date:"d M, Y"}}</td>
					<td>{{project.end_estimated | date:"d M, Y"}}</td>
					<td>{{project.get_project_state}}</td>
                    <td>
						<a class="btn btn-primary btn-sm" href="{% url 'projects:update' pk=project.id %}" role="button"><i class="fa fa-edit"></i> Editar</a>
						<button type="button" onclick="deleteModal({{project.id}})" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Remover</button>
						<input type="hidden" id="delete-{{project.id}}" value="{% url 'projects:delete' pk=project.id %}">
                    </td>
                </tr>
        {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<!-- Modal content-->
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Remover</h4>
                <button type="button" class="close" data-dismiss="modal"><span>×</span></button>

            </div>
            <div class="modal-body">
                <p>Tem certeza que deseja excluir?</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-danger" id="btn-confirm-delete" href="#" role="button">Sim, Remover</a>
                <button type="button"  class="btn btn-default" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

    <script type="text/javascript">
    function deleteModal(id){
		var deleteUrl = $("#delete-"+id)[0].baseURI + 'delete/' + id ;
        $("#btn-confirm-delete")[0].href = deleteUrl;
		console.log(deleteUrl)
        console.log($("#btn-confirm-delete"))
        $("#deleteModal").modal();
    };
    </script>


{% endblock content %}